//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicFormProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Music
    {
        public int Id { get; set; }
        [Required]
        public string SongName { get; set; }
        public string AlbumName { get; set; }
        [Required]
        public string Artist { get; set; }
        public string Duration { get; set; }
        public Nullable<int> PublishYear { get; set; }
    }
}
